// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: aili

#ifndef _AILI_UI_H
#define _AILI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_NUM;
extern lv_obj_t * ui_NUMC;
extern lv_obj_t * ui_NUMCT;
extern lv_obj_t * ui_WIFI;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_aili_png);    // assets/aili.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
