// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: aili

#include "../ui.h"


// COMPONENT text

lv_obj_t * ui_text_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_text;
    cui_text = lv_label_create(comp_parent);
    lv_obj_set_width(cui_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_text, 3);
    lv_obj_set_y(cui_text, -19);
    lv_obj_set_align(cui_text, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_text, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TEXT_NUM);
    children[UI_COMP_TEXT_TEXT] = cui_text;
    lv_obj_add_event_cb(cui_text, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_text, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_text_create_hook(cui_text);
    return cui_text;
}

