// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: aili

#ifndef _UI_COMP_TEXT_H
#define _UI_COMP_TEXT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT text
#define UI_COMP_TEXT_TEXT 0
#define _UI_COMP_TEXT_NUM 1
lv_obj_t * ui_text_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
