// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: aili

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NUM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NUM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NUM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NUM, 60);
    lv_obj_set_y(ui_NUM, 5);
    lv_obj_set_align(ui_NUM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NUM, "9999");
    lv_obj_set_style_text_font(ui_NUM, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NUM, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_NUMC = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_NUMC, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NUMC) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_NUMC, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NUMC, 150);
    lv_obj_set_height(ui_NUMC, 10);
    lv_obj_set_x(ui_NUMC, 70);
    lv_obj_set_y(ui_NUMC, -68);
    lv_obj_set_align(ui_NUMC, LV_ALIGN_CENTER);


    ui_NUMCT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NUMCT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NUMCT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NUMCT, -40);
    lv_obj_set_y(ui_NUMCT, -68);
    lv_obj_set_align(ui_NUMCT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NUMCT, "100%");
    lv_obj_set_style_text_color(ui_NUMCT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NUMCT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_WIFI = lv_checkbox_create(ui_Screen1);
    // lv_checkbox_set_text(ui_WIFI, "WIFI");
    // lv_obj_set_width(ui_WIFI, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_WIFI, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_WIFI, -120);
    // lv_obj_set_y(ui_WIFI, -68);
    // lv_obj_set_align(ui_WIFI, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_WIFI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    // lv_obj_set_style_text_color(ui_WIFI, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_WIFI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WIFI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFI, -120);
    lv_obj_set_y(ui_WIFI, -68);
    lv_obj_set_align(ui_WIFI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WIFI, "20dbm ");

    ui_logo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_logo, &ui_img_aili_png);
    lv_obj_set_width(ui_logo, 100);
    lv_obj_set_height(ui_logo, 100);
    lv_obj_set_x(ui_logo, -97);
    lv_obj_set_y(ui_logo, -3);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_logo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_logo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 70);
    lv_obj_set_y(ui_Label4, 70);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "2024/06/20  12:12:30");

}
